version: '3.1'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-test-library}
      # DB pass and user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pg_volume:/var/lib/postgresql
    ports:
      - "${DB_PORT:-5432}:5432"
  php-fpm:
    build: ./docker/php-fpm
    depends_on:
      -   database
    restart: always
    volumes:
      - ./:/var/www/iactions-library
    environment:
      PHP_IDE_CONFIG:  serverName=Docker
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./:/var/www/iactions-library
    depends_on:
      - php-fpm
    ports:
      - "${APP_PORT:-88}:80"

volumes:
  pg_volume:
    external: true